// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: MBMS_Display

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
lv_obj_t * ui_HomeScreen;
void ui_event_ContactorStatusBtn(lv_event_t * e);
lv_obj_t * ui_ContactorStatusBtn;
lv_obj_t * ui_ContactorStatusLabel;
lv_obj_t * ui_TripBtn;
lv_obj_t * ui_TripLabel;
lv_obj_t * ui_BatteryBtn;
lv_obj_t * ui_BatteryLabel;
lv_obj_t * ui_MBMSBtn;
lv_obj_t * ui_MBMSLabel;
lv_obj_t * ui_PowerSelectBtn;
lv_obj_t * ui_PowerSelectLabel;
// CUSTOM VARIABLES


// SCREEN: ui_Contactor_Screen
void ui_Contactor_Screen_screen_init(void);
lv_obj_t * ui_Contactor_Screen;
lv_obj_t * ui_TableHeader;
lv_obj_t * ui_ContactorTableHeader;
lv_obj_t * ui_StateTableHeader;
lv_obj_t * ui_AmpTableHeader;
lv_obj_t * ui_VoltTableHeader;
lv_obj_t * ui_HeartbeatIcon;
lv_obj_t * ui_CommonRowContainer;
lv_obj_t * ui_CommonCheck;
lv_obj_t * ui_CommonContactorLabel;
lv_obj_t * ui_CommonState;
lv_obj_t * ui_CommonA;
lv_obj_t * ui_CommonV;
lv_obj_t * ui_MotorRowContainer;
lv_obj_t * ui_MotorContactorLabel;
lv_obj_t * ui_MotorState;
lv_obj_t * ui_MotorCheck;
lv_obj_t * ui_MotorA;
lv_obj_t * ui_MotorV;
lv_obj_t * ui_ArrayRowContainer;
lv_obj_t * ui_ArrayContactorLabel;
lv_obj_t * ui_ArrayState;
lv_obj_t * ui_ArrayCheck;
lv_obj_t * ui_ArrayA;
lv_obj_t * ui_ArrayV;
lv_obj_t * ui_LowVRowContainer;
lv_obj_t * ui_LowVContactorLabel;
lv_obj_t * ui_LowVState;
lv_obj_t * ui_LowVCheck;
lv_obj_t * ui_LowVA;
lv_obj_t * ui_LowVV;
lv_obj_t * ui_ChargeRowContainer;
lv_obj_t * ui_ChargeContactorLabel;
lv_obj_t * ui_ChargeState;
lv_obj_t * ui_ChargeCheck;
lv_obj_t * ui_ChargeA;
lv_obj_t * ui_ChargeV;
lv_obj_t * ui_PreChargerRowContainer;
lv_obj_t * ui_PreChargerContactorLabel;
lv_obj_t * ui_PreChargerState;
lv_obj_t * ui_PreChargerCheck;
lv_obj_t * ui_PreChargerA;
lv_obj_t * ui_PreChargerV;
lv_obj_t * ui_ContactorColumnContainer;
lv_obj_t * ui_StateColumnContainer;
lv_obj_t * ui_HeartbeatColumnContainer;
lv_obj_t * ui_AmpColumnContainer;
// CUSTOM VARIABLES


// SCREEN: ui_TripScreen
void ui_TripScreen_screen_init(void);
lv_obj_t * ui_TripScreen;
lv_obj_t * ui_HighCellVoltageTrip;
lv_obj_t * ui_LowCellVoltageTrip;
lv_obj_t * ui_Header;
lv_obj_t * ui_CommonHighCurrTrip;
lv_obj_t * ui_MotorHighCurrTrip;
lv_obj_t * ui_ArrayHighCurrTrip;
lv_obj_t * ui_LVHighCurrTrip;
lv_obj_t * ui_ChargeHighCurrTrip;
lv_obj_t * ui_ProtectionTrip;
lv_obj_t * ui_OrionMsgTimeoutTrip;
lv_obj_t * ui_HighBatteryTrip;
lv_obj_t * ui_ESDEnabledTrip;
lv_obj_t * ui_HighTempTrip;
lv_obj_t * ui_MPSDisabledTrip;
lv_obj_t * ui_LowTempTrip;
lv_obj_t * ui_CommonHeartBeatTrip;
lv_obj_t * ui_MotorHeartbeatTrip;
lv_obj_t * ui_ArrayHeartbeatTrip;
lv_obj_t * ui_ChargeHeartbeatTrip;
lv_obj_t * ui_ContactorDisconnectedUnexpectedlyTrip;
lv_obj_t * ui_ContactorConnectedUnexpectedlyTrip;
lv_obj_t * ui_LVHeartBeatTrip;
// CUSTOM VARIABLES


// SCREEN: ui_BatteryInfoScreen
void ui_BatteryInfoScreen_screen_init(void);
lv_obj_t * ui_BatteryInfoScreen;
lv_obj_t * ui_AmphoursLabel;
lv_obj_t * ui_PackCurrentVLabel;
lv_obj_t * ui_PackCurrentALabel;
lv_obj_t * ui_StateOfChargeLabel;
lv_obj_t * ui_LowTempLabel;
lv_obj_t * ui_MaxCellVoltageLabel;
lv_obj_t * ui_AvgTempLabel;
lv_obj_t * ui_HighTempLabel;
lv_obj_t * ui_MinCellVoltageLabel;
lv_obj_t * ui_MaxPackVoltageLabel;
lv_obj_t * ui_MinPackVoltageLabel;
lv_obj_t * ui_DepthofDischargeLabel;
lv_obj_t * ui_PackCurrentVal;
lv_obj_t * ui_AmpHoursVal;
lv_obj_t * ui_PackVoltageVal;
lv_obj_t * ui_StateOfChargeVal;
lv_obj_t * ui_DepthOfDischargeVal;
lv_obj_t * ui_LowTempVal;
lv_obj_t * ui_AvgTempVal;
lv_obj_t * ui_HighTempVal;
lv_obj_t * ui_MaxCellVoltageVal;
lv_obj_t * ui_MinPackVoltageVal;
lv_obj_t * ui_MinCellVoltageVal;
lv_obj_t * ui_MaxPackVoltageVal;
lv_obj_t * ui_BatteryInfoHeader;
// CUSTOM VARIABLES


// SCREEN: ui_MBMSStatusScreen
void ui_MBMSStatusScreen_screen_init(void);
lv_obj_t * ui_MBMSStatusScreen;
lv_obj_t * ui_AllowChargeCheck;
lv_obj_t * ui_AuxiliaryBatteryVoltageLabel;
lv_obj_t * ui_OrionCanReceivedCheck;
lv_obj_t * ui_DischargeShouldTripCheck;
lv_obj_t * ui_ChargeShouldTripCheck;
lv_obj_t * ui_StrobeBMSLightCheck;
lv_obj_t * ui_StartupStateLabel;
lv_obj_t * ui_AllowDischargeCheck;
lv_obj_t * ui_ChargeSafetyCheck;
lv_obj_t * ui_AuxBatteryVoltageVal;
lv_obj_t * ui_StartupStateVal;
lv_obj_t * ui_MBMSStatusHeader;
lv_obj_t * ui_HighVoltageEnableStateCheck;
// CUSTOM VARIABLES


// SCREEN: ui_PowerSelectionStatusScreen
void ui_PowerSelectionStatusScreen_screen_init(void);
lv_obj_t * ui_PowerSelectionStatusScreen;
lv_obj_t * ui_MainPowerSwitchPanel;
lv_obj_t * ui_MainPowerSwitchVal;
lv_obj_t * ui_MainPowerSwitchLabel;
lv_obj_t * ui_EN1Panel;
lv_obj_t * ui_EN1Val;
lv_obj_t * ui_EN1Label;
lv_obj_t * ui_ExternalShutdownCheck;
lv_obj_t * ui_DCDCFaultCheck;
lv_obj_t * ui_DCDCOnCheck;
lv_obj_t * ui_ChargeFaultCheck;
lv_obj_t * ui_ChargeOnCheck;
lv_obj_t * ui_ThreeAmpOverCurrentCheck;
lv_obj_t * ui_KeyPanel;
lv_obj_t * ui_KeyLabel;
lv_obj_t * ui_KeyVal;
lv_obj_t * ui_ChargeLVEnableCheck;
lv_obj_t * ui_AuxBattDisableCheck;
lv_obj_t * ui_Label22;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ContactorStatusBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Contactor_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_Contactor_Screen_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_HomeScreen_screen_init();
    ui_Contactor_Screen_screen_init();
    ui_TripScreen_screen_init();
    ui_BatteryInfoScreen_screen_init();
    ui_MBMSStatusScreen_screen_init();
    // ui_PowerSelectionStatusScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_HomeScreen);
}
