// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: MBMS_Display

#include "ui.h"

void ui_Contactor_Screen_screen_init(void)
{
    ui_Contactor_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Contactor_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TableHeader = lv_obj_create(ui_Contactor_Screen);
    lv_obj_remove_style_all(ui_TableHeader);
    lv_obj_set_width(ui_TableHeader, 320);
    lv_obj_set_height(ui_TableHeader, 50);
    lv_obj_set_x(ui_TableHeader, 0);
    lv_obj_set_y(ui_TableHeader, -93);
    lv_obj_set_align(ui_TableHeader, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TableHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TableHeader, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TableHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TableHeader, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TableHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TableHeader, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContactorTableHeader = lv_label_create(ui_Contactor_Screen);
    lv_obj_set_width(ui_ContactorTableHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ContactorTableHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ContactorTableHeader, -109);
    lv_obj_set_y(ui_ContactorTableHeader, -92);
    lv_obj_set_align(ui_ContactorTableHeader, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ContactorTableHeader, "Contactor");
    lv_obj_set_style_text_font(ui_ContactorTableHeader, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StateTableHeader = lv_label_create(ui_Contactor_Screen);
    lv_obj_set_width(ui_StateTableHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StateTableHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StateTableHeader, -23);
    lv_obj_set_y(ui_StateTableHeader, -91);
    lv_obj_set_align(ui_StateTableHeader, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StateTableHeader, "State");
    lv_obj_set_style_text_font(ui_StateTableHeader, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LineAmpTableHeader = lv_label_create(ui_Contactor_Screen);
    lv_obj_set_width(ui_LineAmpTableHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LineAmpTableHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LineAmpTableHeader, 85);
    lv_obj_set_y(ui_LineAmpTableHeader, -92);
    lv_obj_set_align(ui_LineAmpTableHeader, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LineAmpTableHeader, "LA");
    lv_obj_set_style_text_font(ui_LineAmpTableHeader, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChargeCurrentTableHeader = lv_label_create(ui_Contactor_Screen);
    lv_obj_set_width(ui_ChargeCurrentTableHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChargeCurrentTableHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChargeCurrentTableHeader, 132);
    lv_obj_set_y(ui_ChargeCurrentTableHeader, -92);
    lv_obj_set_align(ui_ChargeCurrentTableHeader, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ChargeCurrentTableHeader, "CA");
    lv_obj_set_style_text_font(ui_ChargeCurrentTableHeader, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeartbeatIcon = lv_img_create(ui_Contactor_Screen);
    lv_img_set_src(ui_HeartbeatIcon, &ui_img_heart_app_icon_red_outline_black_background_png);
    lv_obj_set_width(ui_HeartbeatIcon, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_HeartbeatIcon, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_HeartbeatIcon, 37);
    lv_obj_set_y(ui_HeartbeatIcon, -93);
    lv_obj_set_align(ui_HeartbeatIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HeartbeatIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HeartbeatIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_HeartbeatIcon, 16);

    ui_CommonRowContainer = lv_obj_create(ui_Contactor_Screen);
    lv_obj_remove_style_all(ui_CommonRowContainer);
    lv_obj_set_width(ui_CommonRowContainer, 320);
    lv_obj_set_height(ui_CommonRowContainer, 30);
    lv_obj_set_x(ui_CommonRowContainer, 0);
    lv_obj_set_y(ui_CommonRowContainer, -53);
    lv_obj_set_align(ui_CommonRowContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CommonRowContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CommonRowContainer, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CommonRowContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CommonRowContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CommonRowContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CommonRowContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CommonCheck = lv_checkbox_create(ui_Contactor_Screen);
    lv_checkbox_set_text(ui_CommonCheck, "");
    lv_obj_set_width(ui_CommonCheck, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CommonCheck, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CommonCheck, 44);
    lv_obj_set_y(ui_CommonCheck, -53);
    lv_obj_set_align(ui_CommonCheck, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CommonCheck, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_bg_color(ui_CommonCheck, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CommonCheck, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CommonCheck, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CommonCheck, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_CommonContactorLabel = lv_label_create(ui_Contactor_Screen);
    lv_obj_set_width(ui_CommonContactorLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CommonContactorLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CommonContactorLabel, -108);
    lv_obj_set_y(ui_CommonContactorLabel, -52);
    lv_obj_set_align(ui_CommonContactorLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CommonContactorLabel, "Common");

    ui_CommonState = lv_label_create(ui_Contactor_Screen);
    lv_obj_set_width(ui_CommonState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CommonState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CommonState, -18);
    lv_obj_set_y(ui_CommonState, -52);
    lv_obj_set_align(ui_CommonState, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CommonState, "OPEN");

    ui_CommonLA = lv_label_create(ui_Contactor_Screen);
    lv_obj_set_width(ui_CommonLA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CommonLA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CommonLA, 85);
    lv_obj_set_y(ui_CommonLA, -52);
    lv_obj_set_align(ui_CommonLA, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CommonLA, "5.5");

    ui_CommonCA = lv_label_create(ui_Contactor_Screen);
    lv_obj_set_width(ui_CommonCA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CommonCA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CommonCA, 132);
    lv_obj_set_y(ui_CommonCA, -52);
    lv_obj_set_align(ui_CommonCA, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CommonCA, "12.2");

    ui_MotorRowContainer = lv_obj_create(ui_Contactor_Screen);
    lv_obj_remove_style_all(ui_MotorRowContainer);
    lv_obj_set_width(ui_MotorRowContainer, 320);
    lv_obj_set_height(ui_MotorRowContainer, 30);
    lv_obj_set_x(ui_MotorRowContainer, 0);
    lv_obj_set_y(ui_MotorRowContainer, -25);
    lv_obj_set_align(ui_MotorRowContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MotorRowContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MotorRowContainer, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MotorRowContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MotorRowContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MotorRowContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MotorRowContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorContactorLabel = lv_label_create(ui_Contactor_Screen);
    lv_obj_set_width(ui_MotorContactorLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorContactorLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorContactorLabel, -108);
    lv_obj_set_y(ui_MotorContactorLabel, -25);
    lv_obj_set_align(ui_MotorContactorLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MotorContactorLabel, "Motor");

    ui_MotorState = lv_label_create(ui_Contactor_Screen);
    lv_obj_set_width(ui_MotorState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorState, -19);
    lv_obj_set_y(ui_MotorState, -25);
    lv_obj_set_align(ui_MotorState, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MotorState, "CLOSED");

    ui_MotorCheck = lv_checkbox_create(ui_Contactor_Screen);
    lv_checkbox_set_text(ui_MotorCheck, "");
    lv_obj_set_width(ui_MotorCheck, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorCheck, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorCheck, 44);
    lv_obj_set_y(ui_MotorCheck, -25);
    lv_obj_set_align(ui_MotorCheck, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_MotorCheck, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_MotorCheck, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_bg_color(ui_MotorCheck, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MotorCheck, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MotorCheck, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MotorCheck, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_MotorLA = lv_label_create(ui_Contactor_Screen);
    lv_obj_set_width(ui_MotorLA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorLA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorLA, 85);
    lv_obj_set_y(ui_MotorLA, -25);
    lv_obj_set_align(ui_MotorLA, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MotorLA, "5.5");

    ui_MotorCA = lv_label_create(ui_Contactor_Screen);
    lv_obj_set_width(ui_MotorCA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorCA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorCA, 132);
    lv_obj_set_y(ui_MotorCA, -25);
    lv_obj_set_align(ui_MotorCA, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MotorCA, "12.2");

    ui_ArrayRowContainer = lv_obj_create(ui_Contactor_Screen);
    lv_obj_remove_style_all(ui_ArrayRowContainer);
    lv_obj_set_width(ui_ArrayRowContainer, 320);
    lv_obj_set_height(ui_ArrayRowContainer, 30);
    lv_obj_set_x(ui_ArrayRowContainer, 0);
    lv_obj_set_y(ui_ArrayRowContainer, 4);
    lv_obj_set_align(ui_ArrayRowContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ArrayRowContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ArrayRowContainer, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArrayRowContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ArrayRowContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ArrayRowContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ArrayRowContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArrayContactorLabel = lv_label_create(ui_Contactor_Screen);
    lv_obj_set_width(ui_ArrayContactorLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArrayContactorLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArrayContactorLabel, -108);
    lv_obj_set_y(ui_ArrayContactorLabel, 3);
    lv_obj_set_align(ui_ArrayContactorLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArrayContactorLabel, "Array");

    ui_ArrayState = lv_label_create(ui_Contactor_Screen);
    lv_obj_set_width(ui_ArrayState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArrayState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArrayState, -19);
    lv_obj_set_y(ui_ArrayState, 3);
    lv_obj_set_align(ui_ArrayState, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArrayState, "CLOSED");

    ui_ArrayCheck = lv_checkbox_create(ui_Contactor_Screen);
    lv_checkbox_set_text(ui_ArrayCheck, "");
    lv_obj_set_width(ui_ArrayCheck, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArrayCheck, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArrayCheck, 44);
    lv_obj_set_y(ui_ArrayCheck, 3);
    lv_obj_set_align(ui_ArrayCheck, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_ArrayCheck, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_ArrayCheck, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_bg_color(ui_ArrayCheck, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArrayCheck, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ArrayCheck, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ArrayCheck, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ArrayLA = lv_label_create(ui_Contactor_Screen);
    lv_obj_set_width(ui_ArrayLA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArrayLA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArrayLA, 85);
    lv_obj_set_y(ui_ArrayLA, 3);
    lv_obj_set_align(ui_ArrayLA, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArrayLA, "5.5");

    ui_ArrayCA = lv_label_create(ui_Contactor_Screen);
    lv_obj_set_width(ui_ArrayCA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArrayCA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArrayCA, 132);
    lv_obj_set_y(ui_ArrayCA, 3);
    lv_obj_set_align(ui_ArrayCA, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArrayCA, "12.2");

    ui_LowVRowContainer = lv_obj_create(ui_Contactor_Screen);
    lv_obj_remove_style_all(ui_LowVRowContainer);
    lv_obj_set_width(ui_LowVRowContainer, 320);
    lv_obj_set_height(ui_LowVRowContainer, 30);
    lv_obj_set_x(ui_LowVRowContainer, 0);
    lv_obj_set_y(ui_LowVRowContainer, 34);
    lv_obj_set_align(ui_LowVRowContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LowVRowContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LowVRowContainer, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LowVRowContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LowVRowContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LowVRowContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LowVRowContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LowVContactorLabel = lv_label_create(ui_Contactor_Screen);
    lv_obj_set_width(ui_LowVContactorLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LowVContactorLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LowVContactorLabel, -108);
    lv_obj_set_y(ui_LowVContactorLabel, 34);
    lv_obj_set_align(ui_LowVContactorLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LowVContactorLabel, "LowV");

    ui_LowVState = lv_label_create(ui_Contactor_Screen);
    lv_obj_set_width(ui_LowVState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LowVState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LowVState, -19);
    lv_obj_set_y(ui_LowVState, 34);
    lv_obj_set_align(ui_LowVState, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LowVState, "CLOSED");

    ui_LowVCheck = lv_checkbox_create(ui_Contactor_Screen);
    lv_checkbox_set_text(ui_LowVCheck, "");
    lv_obj_set_width(ui_LowVCheck, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LowVCheck, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LowVCheck, 44);
    lv_obj_set_y(ui_LowVCheck, 33);
    lv_obj_set_align(ui_LowVCheck, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LowVCheck, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_bg_color(ui_LowVCheck, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LowVCheck, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LowVCheck, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LowVCheck, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LowVLA = lv_label_create(ui_Contactor_Screen);
    lv_obj_set_width(ui_LowVLA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LowVLA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LowVLA, 85);
    lv_obj_set_y(ui_LowVLA, 33);
    lv_obj_set_align(ui_LowVLA, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LowVLA, "5.5");

    ui_LowVCA = lv_label_create(ui_Contactor_Screen);
    lv_obj_set_width(ui_LowVCA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LowVCA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LowVCA, 132);
    lv_obj_set_y(ui_LowVCA, 33);
    lv_obj_set_align(ui_LowVCA, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LowVCA, "12.2");

    ui_ChargeRowContainer = lv_obj_create(ui_Contactor_Screen);
    lv_obj_remove_style_all(ui_ChargeRowContainer);
    lv_obj_set_width(ui_ChargeRowContainer, 320);
    lv_obj_set_height(ui_ChargeRowContainer, 30);
    lv_obj_set_x(ui_ChargeRowContainer, 0);
    lv_obj_set_y(ui_ChargeRowContainer, 64);
    lv_obj_set_align(ui_ChargeRowContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ChargeRowContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ChargeRowContainer, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChargeRowContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ChargeRowContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ChargeRowContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ChargeRowContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChargeContactorLabel = lv_label_create(ui_Contactor_Screen);
    lv_obj_set_width(ui_ChargeContactorLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChargeContactorLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChargeContactorLabel, -108);
    lv_obj_set_y(ui_ChargeContactorLabel, 64);
    lv_obj_set_align(ui_ChargeContactorLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ChargeContactorLabel, "Charge");

    ui_ChargeState = lv_label_create(ui_Contactor_Screen);
    lv_obj_set_width(ui_ChargeState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChargeState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChargeState, -19);
    lv_obj_set_y(ui_ChargeState, 64);
    lv_obj_set_align(ui_ChargeState, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ChargeState, "CLOSED");

    ui_ChargeCheck = lv_checkbox_create(ui_Contactor_Screen);
    lv_checkbox_set_text(ui_ChargeCheck, "");
    lv_obj_set_width(ui_ChargeCheck, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChargeCheck, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChargeCheck, 44);
    lv_obj_set_y(ui_ChargeCheck, 64);
    lv_obj_set_align(ui_ChargeCheck, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChargeCheck, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    lv_obj_set_style_bg_color(ui_ChargeCheck, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChargeCheck, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ChargeCheck, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ChargeCheck, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ChargeLA = lv_label_create(ui_Contactor_Screen);
    lv_obj_set_width(ui_ChargeLA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChargeLA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChargeLA, 85);
    lv_obj_set_y(ui_ChargeLA, 64);
    lv_obj_set_align(ui_ChargeLA, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ChargeLA, "5.5");

    ui_ChargeCA = lv_label_create(ui_Contactor_Screen);
    lv_obj_set_width(ui_ChargeCA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChargeCA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChargeCA, 132);
    lv_obj_set_y(ui_ChargeCA, 64);
    lv_obj_set_align(ui_ChargeCA, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ChargeCA, "12.2");

    ui_ContactorColumnContainer = lv_obj_create(ui_Contactor_Screen);
    lv_obj_remove_style_all(ui_ContactorColumnContainer);
    lv_obj_set_width(ui_ContactorColumnContainer, 1);
    lv_obj_set_height(ui_ContactorColumnContainer, 196);
    lv_obj_set_x(ui_ContactorColumnContainer, -58);
    lv_obj_set_y(ui_ContactorColumnContainer, -20);
    lv_obj_set_align(ui_ContactorColumnContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContactorColumnContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ContactorColumnContainer, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContactorColumnContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ContactorColumnContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContactorColumnContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContactorColumnContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StateColumnContainer = lv_obj_create(ui_Contactor_Screen);
    lv_obj_remove_style_all(ui_StateColumnContainer);
    lv_obj_set_width(ui_StateColumnContainer, 1);
    lv_obj_set_height(ui_StateColumnContainer, 196);
    lv_obj_set_x(ui_StateColumnContainer, 16);
    lv_obj_set_y(ui_StateColumnContainer, -20);
    lv_obj_set_align(ui_StateColumnContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_StateColumnContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_StateColumnContainer, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StateColumnContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_StateColumnContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_StateColumnContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StateColumnContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeartbeatColumnContainer = lv_obj_create(ui_Contactor_Screen);
    lv_obj_remove_style_all(ui_HeartbeatColumnContainer);
    lv_obj_set_width(ui_HeartbeatColumnContainer, 1);
    lv_obj_set_height(ui_HeartbeatColumnContainer, 196);
    lv_obj_set_x(ui_HeartbeatColumnContainer, 62);
    lv_obj_set_y(ui_HeartbeatColumnContainer, -20);
    lv_obj_set_align(ui_HeartbeatColumnContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HeartbeatColumnContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HeartbeatColumnContainer, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeartbeatColumnContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HeartbeatColumnContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HeartbeatColumnContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HeartbeatColumnContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AmpColumnContainer = lv_obj_create(ui_Contactor_Screen);
    lv_obj_remove_style_all(ui_AmpColumnContainer);
    lv_obj_set_width(ui_AmpColumnContainer, 1);
    lv_obj_set_height(ui_AmpColumnContainer, 196);
    lv_obj_set_x(ui_AmpColumnContainer, 109);
    lv_obj_set_y(ui_AmpColumnContainer, -20);
    lv_obj_set_align(ui_AmpColumnContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AmpColumnContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AmpColumnContainer, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AmpColumnContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AmpColumnContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_AmpColumnContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_AmpColumnContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);



}
