// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: MBMS_Display

#include "ui.h"

void ui_MBMSStatusScreen_screen_init(void)
{
    ui_MBMSStatusScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MBMSStatusScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AllowChargeCheck = lv_checkbox_create(ui_MBMSStatusScreen);
    lv_checkbox_set_text(ui_AllowChargeCheck, "Allow Charge");
    lv_obj_set_width(ui_AllowChargeCheck, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AllowChargeCheck, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AllowChargeCheck, -92);
    lv_obj_set_y(ui_AllowChargeCheck, 21);
    lv_obj_set_align(ui_AllowChargeCheck, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AllowChargeCheck, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_add_state(ui_AllowChargeCheck, LV_STATE_CHECKED);       /// States

    ui_AuxiliaryBatteryVoltageLabel = lv_label_create(ui_MBMSStatusScreen);
    lv_obj_set_width(ui_AuxiliaryBatteryVoltageLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AuxiliaryBatteryVoltageLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AuxiliaryBatteryVoltageLabel, -67);
    lv_obj_set_y(ui_AuxiliaryBatteryVoltageLabel, -62);
    lv_obj_set_align(ui_AuxiliaryBatteryVoltageLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AuxiliaryBatteryVoltageLabel, "Auxiliary Battery Voltage");

    ui_OrionCanReceivedCheck = lv_checkbox_create(ui_MBMSStatusScreen);
    lv_checkbox_set_text(ui_OrionCanReceivedCheck, "Orion CAN Received");
    lv_obj_set_width(ui_OrionCanReceivedCheck, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OrionCanReceivedCheck, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OrionCanReceivedCheck, -15);
    lv_obj_set_y(ui_OrionCanReceivedCheck, 48);
    lv_obj_set_align(ui_OrionCanReceivedCheck, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OrionCanReceivedCheck, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_add_state(ui_OrionCanReceivedCheck, LV_STATE_CHECKED);       /// States

    ui_DischargeShouldTripCheck = lv_checkbox_create(ui_MBMSStatusScreen);
    lv_checkbox_set_text(ui_DischargeShouldTripCheck, "Discharge Should Trip");
    lv_obj_set_width(ui_DischargeShouldTripCheck, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DischargeShouldTripCheck, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DischargeShouldTripCheck, -7);
    lv_obj_set_y(ui_DischargeShouldTripCheck, 73);
    lv_obj_set_align(ui_DischargeShouldTripCheck, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DischargeShouldTripCheck, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_add_state(ui_DischargeShouldTripCheck, LV_STATE_CHECKED);       /// States

    ui_ChargeShouldTripCheck = lv_checkbox_create(ui_MBMSStatusScreen);
    lv_checkbox_set_text(ui_ChargeShouldTripCheck, "Charge Should Trip");
    lv_obj_set_width(ui_ChargeShouldTripCheck, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChargeShouldTripCheck, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChargeShouldTripCheck, -18);
    lv_obj_set_y(ui_ChargeShouldTripCheck, 99);
    lv_obj_set_align(ui_ChargeShouldTripCheck, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChargeShouldTripCheck, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_add_state(ui_ChargeShouldTripCheck, LV_STATE_CHECKED);       /// States

    ui_StrobeBMSLightCheck = lv_checkbox_create(ui_MBMSStatusScreen);
    lv_checkbox_set_text(ui_StrobeBMSLightCheck, "Strobe BMS Light");
    lv_obj_set_width(ui_StrobeBMSLightCheck, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StrobeBMSLightCheck, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StrobeBMSLightCheck, -75);
    lv_obj_set_y(ui_StrobeBMSLightCheck, -5);
    lv_obj_set_align(ui_StrobeBMSLightCheck, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StrobeBMSLightCheck, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_add_state(ui_StrobeBMSLightCheck, LV_STATE_CHECKED);       /// States

    ui_StartupStateLabel = lv_label_create(ui_MBMSStatusScreen);
    lv_obj_set_width(ui_StartupStateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StartupStateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StartupStateLabel, 104);
    lv_obj_set_y(ui_StartupStateLabel, -62);
    lv_obj_set_align(ui_StartupStateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StartupStateLabel, "Startup State");

    ui_AllowDischargeCheck = lv_checkbox_create(ui_MBMSStatusScreen);
    lv_checkbox_set_text(ui_AllowDischargeCheck, "Allow Discharge");
    lv_obj_set_width(ui_AllowDischargeCheck, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AllowDischargeCheck, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AllowDischargeCheck, 81);
    lv_obj_set_y(ui_AllowDischargeCheck, 19);
    lv_obj_set_align(ui_AllowDischargeCheck, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AllowDischargeCheck, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_add_state(ui_AllowDischargeCheck, LV_STATE_CHECKED);       /// States

    ui_ChargeSafetyCheck = lv_checkbox_create(ui_MBMSStatusScreen);
    lv_checkbox_set_text(ui_ChargeSafetyCheck, "Charge Safety");
    lv_obj_set_width(ui_ChargeSafetyCheck, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChargeSafetyCheck, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChargeSafetyCheck, 74);
    lv_obj_set_y(ui_ChargeSafetyCheck, -6);
    lv_obj_set_align(ui_ChargeSafetyCheck, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChargeSafetyCheck, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_add_state(ui_ChargeSafetyCheck, LV_STATE_CHECKED);       /// States

    ui_AuxBatteryVoltageVal = lv_label_create(ui_MBMSStatusScreen);
    lv_obj_set_width(ui_AuxBatteryVoltageVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AuxBatteryVoltageVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AuxBatteryVoltageVal, -71);
    lv_obj_set_y(ui_AuxBatteryVoltageVal, -83);
    lv_obj_set_align(ui_AuxBatteryVoltageVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AuxBatteryVoltageVal, "14 V");
    lv_obj_set_style_text_color(ui_AuxBatteryVoltageVal, lv_color_hex(0xF1FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AuxBatteryVoltageVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StartupStateVal = lv_label_create(ui_MBMSStatusScreen);
    lv_obj_set_width(ui_StartupStateVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StartupStateVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StartupStateVal, 95);
    lv_obj_set_y(ui_StartupStateVal, -80);
    lv_obj_set_align(ui_StartupStateVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StartupStateVal, "FAULTS_CLEARED");
    lv_obj_set_style_text_color(ui_StartupStateVal, lv_color_hex(0xF1FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StartupStateVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MBMSStatusHeader = lv_label_create(ui_MBMSStatusScreen);
    lv_obj_set_width(ui_MBMSStatusHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MBMSStatusHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MBMSStatusHeader, -3);
    lv_obj_set_y(ui_MBMSStatusHeader, -109);
    lv_obj_set_align(ui_MBMSStatusHeader, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MBMSStatusHeader, "MBMS Status");
    lv_obj_set_style_text_color(ui_MBMSStatusHeader, lv_color_hex(0x08C229), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MBMSStatusHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MBMSStatusHeader, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HighVoltageEnableStateCheck = lv_checkbox_create(ui_MBMSStatusScreen);
    lv_checkbox_set_text(ui_HighVoltageEnableStateCheck, "High Voltage Enable State");
    lv_obj_set_width(ui_HighVoltageEnableStateCheck, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HighVoltageEnableStateCheck, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HighVoltageEnableStateCheck, 5);
    lv_obj_set_y(ui_HighVoltageEnableStateCheck, -29);
    lv_obj_set_align(ui_HighVoltageEnableStateCheck, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HighVoltageEnableStateCheck, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_add_state(ui_HighVoltageEnableStateCheck, LV_STATE_CHECKED);       /// States

}
