// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: MBMS_Display

#include "ui.h"

void ui_TripScreen_screen_init(void)
{
    ui_TripScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_TripScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HighCellVoltageTrip = lv_checkbox_create(ui_TripScreen);
    lv_checkbox_set_text(ui_HighCellVoltageTrip, "HighCellVolt");
    lv_obj_set_width(ui_HighCellVoltageTrip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HighCellVoltageTrip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HighCellVoltageTrip, -115);
    lv_obj_set_y(ui_HighCellVoltageTrip, -76);
    lv_obj_set_align(ui_HighCellVoltageTrip, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HighCellVoltageTrip, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_HighCellVoltageTrip, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HighCellVoltageTrip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_HighCellVoltageTrip, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_HighCellVoltageTrip, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HighCellVoltageTrip, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HighCellVoltageTrip, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_HighCellVoltageTrip, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HighCellVoltageTrip, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LowCellVoltageTrip = lv_checkbox_create(ui_TripScreen);
    lv_checkbox_set_text(ui_LowCellVoltageTrip, "LowCellVolt");
    lv_obj_set_width(ui_LowCellVoltageTrip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LowCellVoltageTrip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LowCellVoltageTrip, -14);
    lv_obj_set_y(ui_LowCellVoltageTrip, -76);
    lv_obj_set_align(ui_LowCellVoltageTrip, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LowCellVoltageTrip, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_LowCellVoltageTrip, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LowCellVoltageTrip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LowCellVoltageTrip, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LowCellVoltageTrip, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LowCellVoltageTrip, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Header = lv_label_create(ui_TripScreen);
    lv_obj_set_width(ui_Header, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Header, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Header, -7);
    lv_obj_set_y(ui_Header, -104);
    lv_obj_set_align(ui_Header, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Header, "TRIPS");
    lv_obj_set_style_text_color(ui_Header, lv_color_hex(0xEE4400), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Header, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CommonHighCurrTrip = lv_checkbox_create(ui_TripScreen);
    lv_checkbox_set_text(ui_CommonHighCurrTrip, "CommonHighCurr");
    lv_obj_set_width(ui_CommonHighCurrTrip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CommonHighCurrTrip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CommonHighCurrTrip, 98);
    lv_obj_set_y(ui_CommonHighCurrTrip, -76);
    lv_obj_set_align(ui_CommonHighCurrTrip, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CommonHighCurrTrip, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_CommonHighCurrTrip, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CommonHighCurrTrip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CommonHighCurrTrip, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_CommonHighCurrTrip, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CommonHighCurrTrip, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_MotorHighCurrTrip = lv_checkbox_create(ui_TripScreen);
    lv_checkbox_set_text(ui_MotorHighCurrTrip, "MotorHighCurr");
    lv_obj_set_width(ui_MotorHighCurrTrip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorHighCurrTrip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorHighCurrTrip, 89);
    lv_obj_set_y(ui_MotorHighCurrTrip, -48);
    lv_obj_set_align(ui_MotorHighCurrTrip, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MotorHighCurrTrip, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_MotorHighCurrTrip, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MotorHighCurrTrip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MotorHighCurrTrip, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MotorHighCurrTrip, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MotorHighCurrTrip, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ArrayHighCurrTrip = lv_checkbox_create(ui_TripScreen);
    lv_checkbox_set_text(ui_ArrayHighCurrTrip, "ArrayHighCurr");
    lv_obj_set_width(ui_ArrayHighCurrTrip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArrayHighCurrTrip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArrayHighCurrTrip, 87);
    lv_obj_set_y(ui_ArrayHighCurrTrip, -22);
    lv_obj_set_align(ui_ArrayHighCurrTrip, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ArrayHighCurrTrip, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_ArrayHighCurrTrip, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ArrayHighCurrTrip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ArrayHighCurrTrip, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArrayHighCurrTrip, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArrayHighCurrTrip, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LVHighCurrTrip = lv_checkbox_create(ui_TripScreen);
    lv_checkbox_set_text(ui_LVHighCurrTrip, "LVHighCurr");
    lv_obj_set_width(ui_LVHighCurrTrip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LVHighCurrTrip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LVHighCurrTrip, 80);
    lv_obj_set_y(ui_LVHighCurrTrip, 5);
    lv_obj_set_align(ui_LVHighCurrTrip, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LVHighCurrTrip, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_LVHighCurrTrip, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LVHighCurrTrip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LVHighCurrTrip, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LVHighCurrTrip, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LVHighCurrTrip, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ChargeHighCurrTrip = lv_checkbox_create(ui_TripScreen);
    lv_checkbox_set_text(ui_ChargeHighCurrTrip, "ChargeHighCurr");
    lv_obj_set_width(ui_ChargeHighCurrTrip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChargeHighCurrTrip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChargeHighCurrTrip, 92);
    lv_obj_set_y(ui_ChargeHighCurrTrip, 32);
    lv_obj_set_align(ui_ChargeHighCurrTrip, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChargeHighCurrTrip, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_ChargeHighCurrTrip, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChargeHighCurrTrip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChargeHighCurrTrip, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ChargeHighCurrTrip, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChargeHighCurrTrip, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ProtectionTrip = lv_checkbox_create(ui_TripScreen);
    lv_checkbox_set_text(ui_ProtectionTrip, "Protection");
    lv_obj_set_width(ui_ProtectionTrip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ProtectionTrip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ProtectionTrip, 78);
    lv_obj_set_y(ui_ProtectionTrip, 57);
    lv_obj_set_align(ui_ProtectionTrip, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ProtectionTrip, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_ProtectionTrip, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ProtectionTrip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProtectionTrip, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ProtectionTrip, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ProtectionTrip, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_OrionMsgTimeoutTrip = lv_checkbox_create(ui_TripScreen);
    lv_checkbox_set_text(ui_OrionMsgTimeoutTrip, "Orion Message Timeout");
    lv_obj_set_width(ui_OrionMsgTimeoutTrip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OrionMsgTimeoutTrip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OrionMsgTimeoutTrip, -33);
    lv_obj_set_y(ui_OrionMsgTimeoutTrip, 71);
    lv_obj_set_align(ui_OrionMsgTimeoutTrip, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OrionMsgTimeoutTrip, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_OrionMsgTimeoutTrip, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OrionMsgTimeoutTrip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OrionMsgTimeoutTrip, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_OrionMsgTimeoutTrip, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OrionMsgTimeoutTrip, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_HighBatteryTrip = lv_checkbox_create(ui_TripScreen);
    lv_checkbox_set_text(ui_HighBatteryTrip, "HighBattery");
    lv_obj_set_width(ui_HighBatteryTrip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HighBatteryTrip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HighBatteryTrip, -12);
    lv_obj_set_y(ui_HighBatteryTrip, -50);
    lv_obj_set_align(ui_HighBatteryTrip, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HighBatteryTrip, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_HighBatteryTrip, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HighBatteryTrip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_HighBatteryTrip, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_HighBatteryTrip, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_HighBatteryTrip, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HighBatteryTrip, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_HighBatteryTrip, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HighBatteryTrip, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ESDEnabledTrip = lv_checkbox_create(ui_TripScreen);
    lv_checkbox_set_text(ui_ESDEnabledTrip, "ESDEnabled");
    lv_obj_set_width(ui_ESDEnabledTrip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ESDEnabledTrip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ESDEnabledTrip, -11);
    lv_obj_set_y(ui_ESDEnabledTrip, 5);
    lv_obj_set_align(ui_ESDEnabledTrip, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ESDEnabledTrip, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_ESDEnabledTrip, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ESDEnabledTrip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ESDEnabledTrip, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ESDEnabledTrip, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ESDEnabledTrip, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_HighTempTrip = lv_checkbox_create(ui_TripScreen);
    lv_checkbox_set_text(ui_HighTempTrip, "HighTemp");
    lv_obj_set_width(ui_HighTempTrip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HighTempTrip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HighTempTrip, -15);
    lv_obj_set_y(ui_HighTempTrip, 31);
    lv_obj_set_align(ui_HighTempTrip, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HighTempTrip, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_HighTempTrip, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HighTempTrip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HighTempTrip, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_HighTempTrip, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HighTempTrip, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_MPSDisabledTrip = lv_checkbox_create(ui_TripScreen);
    lv_checkbox_set_text(ui_MPSDisabledTrip, "MPSDisabled");
    lv_obj_set_width(ui_MPSDisabledTrip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MPSDisabledTrip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MPSDisabledTrip, -9);
    lv_obj_set_y(ui_MPSDisabledTrip, -22);
    lv_obj_set_align(ui_MPSDisabledTrip, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MPSDisabledTrip, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_MPSDisabledTrip, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MPSDisabledTrip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MPSDisabledTrip, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MPSDisabledTrip, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MPSDisabledTrip, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LowTempTrip = lv_checkbox_create(ui_TripScreen);
    lv_checkbox_set_text(ui_LowTempTrip, "LowTemp");
    lv_obj_set_width(ui_LowTempTrip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LowTempTrip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LowTempTrip, -16);
    lv_obj_set_y(ui_LowTempTrip, 56);
    lv_obj_set_align(ui_LowTempTrip, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LowTempTrip, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_LowTempTrip, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LowTempTrip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LowTempTrip, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LowTempTrip, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LowTempTrip, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_CommonHeartBeatTrip = lv_checkbox_create(ui_TripScreen);
    lv_checkbox_set_text(ui_CommonHeartBeatTrip, "CommonHeart");
    lv_obj_set_width(ui_CommonHeartBeatTrip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CommonHeartBeatTrip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CommonHeartBeatTrip, -109);
    lv_obj_set_y(ui_CommonHeartBeatTrip, -21);
    lv_obj_set_align(ui_CommonHeartBeatTrip, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CommonHeartBeatTrip, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_CommonHeartBeatTrip, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CommonHeartBeatTrip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_CommonHeartBeatTrip, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_CommonHeartBeatTrip, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CommonHeartBeatTrip, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CommonHeartBeatTrip, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_CommonHeartBeatTrip, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CommonHeartBeatTrip, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_MotorHeartbeatTrip = lv_checkbox_create(ui_TripScreen);
    lv_checkbox_set_text(ui_MotorHeartbeatTrip, "MotorHeartbeat");
    lv_obj_set_width(ui_MotorHeartbeatTrip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorHeartbeatTrip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorHeartbeatTrip, -106);
    lv_obj_set_y(ui_MotorHeartbeatTrip, 5);
    lv_obj_set_align(ui_MotorHeartbeatTrip, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MotorHeartbeatTrip, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_MotorHeartbeatTrip, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MotorHeartbeatTrip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_MotorHeartbeatTrip, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_MotorHeartbeatTrip, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_MotorHeartbeatTrip, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MotorHeartbeatTrip, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MotorHeartbeatTrip, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MotorHeartbeatTrip, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ArrayHeartbeatTrip = lv_checkbox_create(ui_TripScreen);
    lv_checkbox_set_text(ui_ArrayHeartbeatTrip, "ArrayHeartbeat");
    lv_obj_set_width(ui_ArrayHeartbeatTrip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArrayHeartbeatTrip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArrayHeartbeatTrip, -107);
    lv_obj_set_y(ui_ArrayHeartbeatTrip, 30);
    lv_obj_set_align(ui_ArrayHeartbeatTrip, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ArrayHeartbeatTrip, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_ArrayHeartbeatTrip, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ArrayHeartbeatTrip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_ArrayHeartbeatTrip, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_ArrayHeartbeatTrip, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ArrayHeartbeatTrip, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ArrayHeartbeatTrip, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArrayHeartbeatTrip, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArrayHeartbeatTrip, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ChargeHeartbeatTrip = lv_checkbox_create(ui_TripScreen);
    lv_checkbox_set_text(ui_ChargeHeartbeatTrip, "ChargeHeart");
    lv_obj_set_width(ui_ChargeHeartbeatTrip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChargeHeartbeatTrip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChargeHeartbeatTrip, -113);
    lv_obj_set_y(ui_ChargeHeartbeatTrip, 54);
    lv_obj_set_align(ui_ChargeHeartbeatTrip, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ChargeHeartbeatTrip, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_ChargeHeartbeatTrip, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChargeHeartbeatTrip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_ChargeHeartbeatTrip, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_ChargeHeartbeatTrip, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ChargeHeartbeatTrip, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChargeHeartbeatTrip, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ChargeHeartbeatTrip, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChargeHeartbeatTrip, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ContactorDisconnectedUnexpectedlyTrip = lv_checkbox_create(ui_TripScreen);
    lv_checkbox_set_text(ui_ContactorDisconnectedUnexpectedlyTrip, "Contactor Disconnected Unexpectedly");
    lv_obj_set_width(ui_ContactorDisconnectedUnexpectedlyTrip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ContactorDisconnectedUnexpectedlyTrip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ContactorDisconnectedUnexpectedlyTrip, 7);
    lv_obj_set_y(ui_ContactorDisconnectedUnexpectedlyTrip, 110);
    lv_obj_set_align(ui_ContactorDisconnectedUnexpectedlyTrip, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ContactorDisconnectedUnexpectedlyTrip, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_ContactorDisconnectedUnexpectedlyTrip, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ContactorDisconnectedUnexpectedlyTrip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_ContactorDisconnectedUnexpectedlyTrip, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_ContactorDisconnectedUnexpectedlyTrip, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ContactorDisconnectedUnexpectedlyTrip, LV_TEXT_ALIGN_AUTO,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ContactorDisconnectedUnexpectedlyTrip, &lv_font_montserrat_10,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ContactorDisconnectedUnexpectedlyTrip, lv_color_hex(0xFFFFFF),
                              LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContactorDisconnectedUnexpectedlyTrip, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ContactorConnectedUnexpectedlyTrip = lv_checkbox_create(ui_TripScreen);
    lv_checkbox_set_text(ui_ContactorConnectedUnexpectedlyTrip, "Contactor Connected Unexpectedly ");
    lv_obj_set_width(ui_ContactorConnectedUnexpectedlyTrip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ContactorConnectedUnexpectedlyTrip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ContactorConnectedUnexpectedlyTrip, 1);
    lv_obj_set_y(ui_ContactorConnectedUnexpectedlyTrip, 90);
    lv_obj_set_align(ui_ContactorConnectedUnexpectedlyTrip, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ContactorConnectedUnexpectedlyTrip, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_ContactorConnectedUnexpectedlyTrip, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ContactorConnectedUnexpectedlyTrip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_ContactorConnectedUnexpectedlyTrip, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_ContactorConnectedUnexpectedlyTrip, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ContactorConnectedUnexpectedlyTrip, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ContactorConnectedUnexpectedlyTrip, &lv_font_montserrat_10,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ContactorConnectedUnexpectedlyTrip, lv_color_hex(0xFFFFFF),
                              LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContactorConnectedUnexpectedlyTrip, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_LVHeartBeatTrip = lv_checkbox_create(ui_TripScreen);
    lv_checkbox_set_text(ui_LVHeartBeatTrip, "LVHeartbeat");
    lv_obj_set_width(ui_LVHeartBeatTrip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LVHeartBeatTrip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LVHeartBeatTrip, -115);
    lv_obj_set_y(ui_LVHeartBeatTrip, -49);
    lv_obj_set_align(ui_LVHeartBeatTrip, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LVHeartBeatTrip, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_LVHeartBeatTrip, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LVHeartBeatTrip, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LVHeartBeatTrip, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LVHeartBeatTrip, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LVHeartBeatTrip, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LVHeartBeatTrip, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LVHeartBeatTrip, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LVHeartBeatTrip, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_MotorHeartbeatVal = lv_label_create(ui_TripScreen);
    lv_obj_set_width(ui_MotorHeartbeatVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorHeartbeatVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorHeartbeatVal, -151);
    lv_obj_set_y(ui_MotorHeartbeatVal, 5);
    lv_obj_set_align(ui_MotorHeartbeatVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MotorHeartbeatVal, "X");
    lv_obj_set_style_text_color(ui_MotorHeartbeatVal, lv_color_hex(0x120CDC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MotorHeartbeatVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MotorHeartbeatVal, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArrayHeartBeatVal = lv_label_create(ui_TripScreen);
    lv_obj_set_width(ui_ArrayHeartBeatVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArrayHeartBeatVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArrayHeartBeatVal, -150);
    lv_obj_set_y(ui_ArrayHeartBeatVal, 30);
    lv_obj_set_align(ui_ArrayHeartBeatVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArrayHeartBeatVal, "X");
    lv_obj_set_style_text_color(ui_ArrayHeartBeatVal, lv_color_hex(0x120CDC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ArrayHeartBeatVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ArrayHeartBeatVal, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChargeHeartBeatVal = lv_label_create(ui_TripScreen);
    lv_obj_set_width(ui_ChargeHeartBeatVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChargeHeartBeatVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChargeHeartBeatVal, -150);
    lv_obj_set_y(ui_ChargeHeartBeatVal, 54);
    lv_obj_set_align(ui_ChargeHeartBeatVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ChargeHeartBeatVal, "X");
    lv_obj_set_style_text_color(ui_ChargeHeartBeatVal, lv_color_hex(0x120CDC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChargeHeartBeatVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChargeHeartBeatVal, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CommonHeartBeatVal = lv_label_create(ui_TripScreen);
    lv_obj_set_width(ui_CommonHeartBeatVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CommonHeartBeatVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CommonHeartBeatVal, -151);
    lv_obj_set_y(ui_CommonHeartBeatVal, -21);
    lv_obj_set_align(ui_CommonHeartBeatVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CommonHeartBeatVal, "X");
    lv_obj_set_style_text_color(ui_CommonHeartBeatVal, lv_color_hex(0x120CDC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CommonHeartBeatVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CommonHeartBeatVal, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LVHeartBeatVal = lv_label_create(ui_TripScreen);
    lv_obj_set_width(ui_LVHeartBeatVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LVHeartBeatVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LVHeartBeatVal, -151);
    lv_obj_set_y(ui_LVHeartBeatVal, -49);
    lv_obj_set_align(ui_LVHeartBeatVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LVHeartBeatVal, "X");
    lv_obj_set_style_text_color(ui_LVHeartBeatVal, lv_color_hex(0x120CDC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LVHeartBeatVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LVHeartBeatVal, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HighCellVoltVal = lv_label_create(ui_TripScreen);
    lv_obj_set_width(ui_HighCellVoltVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HighCellVoltVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HighCellVoltVal, -151);
    lv_obj_set_y(ui_HighCellVoltVal, -76);
    lv_obj_set_align(ui_HighCellVoltVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HighCellVoltVal, "X");
    lv_obj_set_style_text_color(ui_HighCellVoltVal, lv_color_hex(0x120CDC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HighCellVoltVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HighCellVoltVal, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LowCellVoltVal = lv_label_create(ui_TripScreen);
    lv_obj_set_width(ui_LowCellVoltVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LowCellVoltVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LowCellVoltVal, -48);
    lv_obj_set_y(ui_LowCellVoltVal, -76);
    lv_obj_set_align(ui_LowCellVoltVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LowCellVoltVal, "X");
    lv_obj_set_style_text_color(ui_LowCellVoltVal, lv_color_hex(0x120CDC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LowCellVoltVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LowCellVoltVal, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HighBatteryVal = lv_label_create(ui_TripScreen);
    lv_obj_set_width(ui_HighBatteryVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HighBatteryVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HighBatteryVal, -48);
    lv_obj_set_y(ui_HighBatteryVal, -50);
    lv_obj_set_align(ui_HighBatteryVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HighBatteryVal, "X");
    lv_obj_set_style_text_color(ui_HighBatteryVal, lv_color_hex(0x120CDC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HighBatteryVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HighBatteryVal, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MPSDisabledVal = lv_label_create(ui_TripScreen);
    lv_obj_set_width(ui_MPSDisabledVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MPSDisabledVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MPSDisabledVal, -47);
    lv_obj_set_y(ui_MPSDisabledVal, -22);
    lv_obj_set_align(ui_MPSDisabledVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MPSDisabledVal, "X");
    lv_obj_set_style_text_color(ui_MPSDisabledVal, lv_color_hex(0x120CDC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MPSDisabledVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MPSDisabledVal, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ESDEnabledVal = lv_label_create(ui_TripScreen);
    lv_obj_set_width(ui_ESDEnabledVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ESDEnabledVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ESDEnabledVal, -47);
    lv_obj_set_y(ui_ESDEnabledVal, 5);
    lv_obj_set_align(ui_ESDEnabledVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ESDEnabledVal, "X");
    lv_obj_set_style_text_color(ui_ESDEnabledVal, lv_color_hex(0x120CDC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ESDEnabledVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ESDEnabledVal, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HiTempVal = lv_label_create(ui_TripScreen);
    lv_obj_set_width(ui_HiTempVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HiTempVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HiTempVal, -46);
    lv_obj_set_y(ui_HiTempVal, 31);
    lv_obj_set_align(ui_HiTempVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HiTempVal, "X");
    lv_obj_set_style_text_color(ui_HiTempVal, lv_color_hex(0x120CDC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HiTempVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HiTempVal, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LoTempVal = lv_label_create(ui_TripScreen);
    lv_obj_set_width(ui_LoTempVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LoTempVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LoTempVal, -45);
    lv_obj_set_y(ui_LoTempVal, 56);
    lv_obj_set_align(ui_LoTempVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LoTempVal, "X");
    lv_obj_set_style_text_color(ui_LoTempVal, lv_color_hex(0x120CDC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LoTempVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LoTempVal, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ProtectionVal = lv_label_create(ui_TripScreen);
    lv_obj_set_width(ui_ProtectionVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ProtectionVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ProtectionVal, 47);
    lv_obj_set_y(ui_ProtectionVal, 57);
    lv_obj_set_align(ui_ProtectionVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ProtectionVal, "X");
    lv_obj_set_style_text_color(ui_ProtectionVal, lv_color_hex(0x120CDC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ProtectionVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ProtectionVal, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChargeHighCurrVal = lv_label_create(ui_TripScreen);
    lv_obj_set_width(ui_ChargeHighCurrVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChargeHighCurrVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChargeHighCurrVal, 46);
    lv_obj_set_y(ui_ChargeHighCurrVal, 32);
    lv_obj_set_align(ui_ChargeHighCurrVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ChargeHighCurrVal, "X");
    lv_obj_set_style_text_color(ui_ChargeHighCurrVal, lv_color_hex(0x120CDC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChargeHighCurrVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChargeHighCurrVal, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LvHighCurrVal = lv_label_create(ui_TripScreen);
    lv_obj_set_width(ui_LvHighCurrVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LvHighCurrVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LvHighCurrVal, 46);
    lv_obj_set_y(ui_LvHighCurrVal, 5);
    lv_obj_set_align(ui_LvHighCurrVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LvHighCurrVal, "X");
    lv_obj_set_style_text_color(ui_LvHighCurrVal, lv_color_hex(0x120CDC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LvHighCurrVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LvHighCurrVal, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArrayHighCurrVal = lv_label_create(ui_TripScreen);
    lv_obj_set_width(ui_ArrayHighCurrVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ArrayHighCurrVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ArrayHighCurrVal, 46);
    lv_obj_set_y(ui_ArrayHighCurrVal, -22);
    lv_obj_set_align(ui_ArrayHighCurrVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ArrayHighCurrVal, "X");
    lv_obj_set_style_text_color(ui_ArrayHighCurrVal, lv_color_hex(0x120CDC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ArrayHighCurrVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ArrayHighCurrVal, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorHighCurrVal = lv_label_create(ui_TripScreen);
    lv_obj_set_width(ui_MotorHighCurrVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotorHighCurrVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotorHighCurrVal, 46);
    lv_obj_set_y(ui_MotorHighCurrVal, -48);
    lv_obj_set_align(ui_MotorHighCurrVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MotorHighCurrVal, "X");
    lv_obj_set_style_text_color(ui_MotorHighCurrVal, lv_color_hex(0x120CDC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MotorHighCurrVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MotorHighCurrVal, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CommonHighCurrVal = lv_label_create(ui_TripScreen);
    lv_obj_set_width(ui_CommonHighCurrVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CommonHighCurrVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CommonHighCurrVal, 46);
    lv_obj_set_y(ui_CommonHighCurrVal, -76);
    lv_obj_set_align(ui_CommonHighCurrVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CommonHighCurrVal, "X");
    lv_obj_set_style_text_color(ui_CommonHighCurrVal, lv_color_hex(0x120CDC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CommonHighCurrVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CommonHighCurrVal, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OrionMessageTimeoutVal = lv_label_create(ui_TripScreen);
    lv_obj_set_width(ui_OrionMessageTimeoutVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OrionMessageTimeoutVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OrionMessageTimeoutVal, -98);
    lv_obj_set_y(ui_OrionMessageTimeoutVal, 71);
    lv_obj_set_align(ui_OrionMessageTimeoutVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OrionMessageTimeoutVal, "X");
    lv_obj_set_style_text_color(ui_OrionMessageTimeoutVal, lv_color_hex(0x120CDC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OrionMessageTimeoutVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OrionMessageTimeoutVal, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContactorConnectedUnexpectedlyVal = lv_label_create(ui_TripScreen);
    lv_obj_set_width(ui_ContactorConnectedUnexpectedlyVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ContactorConnectedUnexpectedlyVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ContactorConnectedUnexpectedlyVal, -97);
    lv_obj_set_y(ui_ContactorConnectedUnexpectedlyVal, 90);
    lv_obj_set_align(ui_ContactorConnectedUnexpectedlyVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ContactorConnectedUnexpectedlyVal, "X");
    lv_obj_set_style_text_color(ui_ContactorConnectedUnexpectedlyVal, lv_color_hex(0x120CDC),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ContactorConnectedUnexpectedlyVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ContactorConnectedUnexpectedlyVal, &lv_font_montserrat_12,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContactorDisconnectedUnexpectedlyVal = lv_label_create(ui_TripScreen);
    lv_obj_set_width(ui_ContactorDisconnectedUnexpectedlyVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ContactorDisconnectedUnexpectedlyVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ContactorDisconnectedUnexpectedlyVal, -97);
    lv_obj_set_y(ui_ContactorDisconnectedUnexpectedlyVal, 110);
    lv_obj_set_align(ui_ContactorDisconnectedUnexpectedlyVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ContactorDisconnectedUnexpectedlyVal, "X");
    lv_obj_set_style_text_color(ui_ContactorDisconnectedUnexpectedlyVal, lv_color_hex(0x120CDC),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ContactorDisconnectedUnexpectedlyVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ContactorDisconnectedUnexpectedlyVal, &lv_font_montserrat_12,
                               LV_PART_MAIN | LV_STATE_DEFAULT);


}
