// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: MBMS_Display

#include "ui.h"

void ui_BatteryInfoScreen_screen_init(void)
{
    ui_BatteryInfoScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BatteryInfoScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AmphoursLabel = lv_label_create(ui_BatteryInfoScreen);
    lv_obj_set_width(ui_AmphoursLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AmphoursLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AmphoursLabel, 0);
    lv_obj_set_y(ui_AmphoursLabel, -58);
    lv_obj_set_align(ui_AmphoursLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AmphoursLabel, "Amp-hours");

    ui_PackCurrentVLabel = lv_label_create(ui_BatteryInfoScreen);
    lv_obj_set_width(ui_PackCurrentVLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PackCurrentVLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PackCurrentVLabel, 106);
    lv_obj_set_y(ui_PackCurrentVLabel, -73);
    lv_obj_set_align(ui_PackCurrentVLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PackCurrentVLabel, "Pack Voltage");

    ui_PackCurrentALabel = lv_label_create(ui_BatteryInfoScreen);
    lv_obj_set_width(ui_PackCurrentALabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PackCurrentALabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PackCurrentALabel, -106);
    lv_obj_set_y(ui_PackCurrentALabel, -74);
    lv_obj_set_align(ui_PackCurrentALabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PackCurrentALabel, "Pack Current");

    ui_StateOfChargeLabel = lv_label_create(ui_BatteryInfoScreen);
    lv_obj_set_width(ui_StateOfChargeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StateOfChargeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StateOfChargeLabel, -97);
    lv_obj_set_y(ui_StateOfChargeLabel, -26);
    lv_obj_set_align(ui_StateOfChargeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StateOfChargeLabel, "State of Charge");

    ui_LowTempLabel = lv_label_create(ui_BatteryInfoScreen);
    lv_obj_set_width(ui_LowTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LowTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LowTempLabel, -114);
    lv_obj_set_y(ui_LowTempLabel, 21);
    lv_obj_set_align(ui_LowTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LowTempLabel, "Low Temp");

    ui_MaxCellVoltageLabel = lv_label_create(ui_BatteryInfoScreen);
    lv_obj_set_width(ui_MaxCellVoltageLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MaxCellVoltageLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MaxCellVoltageLabel, -94);
    lv_obj_set_y(ui_MaxCellVoltageLabel, 61);
    lv_obj_set_align(ui_MaxCellVoltageLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MaxCellVoltageLabel, "Max Cell Voltage");

    ui_AvgTempLabel = lv_label_create(ui_BatteryInfoScreen);
    lv_obj_set_width(ui_AvgTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AvgTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AvgTempLabel, -2);
    lv_obj_set_y(ui_AvgTempLabel, 20);
    lv_obj_set_align(ui_AvgTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AvgTempLabel, "Avg Temp");

    ui_HighTempLabel = lv_label_create(ui_BatteryInfoScreen);
    lv_obj_set_width(ui_HighTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HighTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HighTempLabel, 108);
    lv_obj_set_y(ui_HighTempLabel, 20);
    lv_obj_set_align(ui_HighTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HighTempLabel, "High Temp");

    ui_MinCellVoltageLabel = lv_label_create(ui_BatteryInfoScreen);
    lv_obj_set_width(ui_MinCellVoltageLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MinCellVoltageLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MinCellVoltageLabel, 91);
    lv_obj_set_y(ui_MinCellVoltageLabel, 61);
    lv_obj_set_align(ui_MinCellVoltageLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MinCellVoltageLabel, "Min Cell Voltage");

    ui_MaxPackVoltageLabel = lv_label_create(ui_BatteryInfoScreen);
    lv_obj_set_width(ui_MaxPackVoltageLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MaxPackVoltageLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MaxPackVoltageLabel, -90);
    lv_obj_set_y(ui_MaxPackVoltageLabel, 101);
    lv_obj_set_align(ui_MaxPackVoltageLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MaxPackVoltageLabel, "Max Pack Voltage");

    ui_MinPackVoltageLabel = lv_label_create(ui_BatteryInfoScreen);
    lv_obj_set_width(ui_MinPackVoltageLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MinPackVoltageLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MinPackVoltageLabel, 92);
    lv_obj_set_y(ui_MinPackVoltageLabel, 101);
    lv_obj_set_align(ui_MinPackVoltageLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MinPackVoltageLabel, "Min Pack Voltage");

    ui_DepthofDischargeLabel = lv_label_create(ui_BatteryInfoScreen);
    lv_obj_set_width(ui_DepthofDischargeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DepthofDischargeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DepthofDischargeLabel, 85);
    lv_obj_set_y(ui_DepthofDischargeLabel, -26);
    lv_obj_set_align(ui_DepthofDischargeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DepthofDischargeLabel, "Depth of Discharge");

    ui_PackCurrentVal = lv_label_create(ui_BatteryInfoScreen);
    lv_obj_set_width(ui_PackCurrentVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PackCurrentVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PackCurrentVal, -108);
    lv_obj_set_y(ui_PackCurrentVal, -91);
    lv_obj_set_align(ui_PackCurrentVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PackCurrentVal, "12.2 A");
    lv_obj_set_style_text_color(ui_PackCurrentVal, lv_color_hex(0xD02424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PackCurrentVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AmpHoursVal = lv_label_create(ui_BatteryInfoScreen);
    lv_obj_set_width(ui_AmpHoursVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AmpHoursVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AmpHoursVal, -1);
    lv_obj_set_y(ui_AmpHoursVal, -76);
    lv_obj_set_align(ui_AmpHoursVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AmpHoursVal, "34 Ah");
    lv_obj_set_style_text_color(ui_AmpHoursVal, lv_color_hex(0x668CFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AmpHoursVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PackVoltageVal = lv_label_create(ui_BatteryInfoScreen);
    lv_obj_set_width(ui_PackVoltageVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PackVoltageVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PackVoltageVal, 106);
    lv_obj_set_y(ui_PackVoltageVal, -91);
    lv_obj_set_align(ui_PackVoltageVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PackVoltageVal, "34 V");
    lv_obj_set_style_text_color(ui_PackVoltageVal, lv_color_hex(0xF1FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PackVoltageVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StateOfChargeVal = lv_label_create(ui_BatteryInfoScreen);
    lv_obj_set_width(ui_StateOfChargeVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StateOfChargeVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StateOfChargeVal, -105);
    lv_obj_set_y(ui_StateOfChargeVal, -43);
    lv_obj_set_align(ui_StateOfChargeVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StateOfChargeVal, "90 %");
    lv_obj_set_style_text_color(ui_StateOfChargeVal, lv_color_hex(0xF1FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StateOfChargeVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DepthOfDischargeVal = lv_label_create(ui_BatteryInfoScreen);
    lv_obj_set_width(ui_DepthOfDischargeVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DepthOfDischargeVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DepthOfDischargeVal, 99);
    lv_obj_set_y(ui_DepthOfDischargeVal, -43);
    lv_obj_set_align(ui_DepthOfDischargeVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DepthOfDischargeVal, "88 %");
    lv_obj_set_style_text_color(ui_DepthOfDischargeVal, lv_color_hex(0xD02424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DepthOfDischargeVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LowTempVal = lv_label_create(ui_BatteryInfoScreen);
    lv_obj_set_width(ui_LowTempVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LowTempVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LowTempVal, -113);
    lv_obj_set_y(ui_LowTempVal, 1);
    lv_obj_set_align(ui_LowTempVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LowTempVal, "18 °C");
    lv_obj_set_style_text_color(ui_LowTempVal, lv_color_hex(0xD02424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LowTempVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AvgTempVal = lv_label_create(ui_BatteryInfoScreen);
    lv_obj_set_width(ui_AvgTempVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AvgTempVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AvgTempVal, -1);
    lv_obj_set_y(ui_AvgTempVal, 1);
    lv_obj_set_align(ui_AvgTempVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AvgTempVal, "27 °C");
    lv_obj_set_style_text_color(ui_AvgTempVal, lv_color_hex(0x668CFC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AvgTempVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HighTempVal = lv_label_create(ui_BatteryInfoScreen);
    lv_obj_set_width(ui_HighTempVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HighTempVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HighTempVal, 107);
    lv_obj_set_y(ui_HighTempVal, 1);
    lv_obj_set_align(ui_HighTempVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HighTempVal, "31 °C");
    lv_obj_set_style_text_color(ui_HighTempVal, lv_color_hex(0xF1FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HighTempVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MaxCellVoltageVal = lv_label_create(ui_BatteryInfoScreen);
    lv_obj_set_width(ui_MaxCellVoltageVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MaxCellVoltageVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MaxCellVoltageVal, -100);
    lv_obj_set_y(ui_MaxCellVoltageVal, 44);
    lv_obj_set_align(ui_MaxCellVoltageVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MaxCellVoltageVal, "2.4 V");
    lv_obj_set_style_text_color(ui_MaxCellVoltageVal, lv_color_hex(0xF1FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MaxCellVoltageVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MinPackVoltageVal = lv_label_create(ui_BatteryInfoScreen);
    lv_obj_set_width(ui_MinPackVoltageVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MinPackVoltageVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MinPackVoltageVal, 89);
    lv_obj_set_y(ui_MinPackVoltageVal, 86);
    lv_obj_set_align(ui_MinPackVoltageVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MinPackVoltageVal, "24 V");
    lv_obj_set_style_text_color(ui_MinPackVoltageVal, lv_color_hex(0xF1FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MinPackVoltageVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MinCellVoltageVal = lv_label_create(ui_BatteryInfoScreen);
    lv_obj_set_width(ui_MinCellVoltageVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MinCellVoltageVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MinCellVoltageVal, 91);
    lv_obj_set_y(ui_MinCellVoltageVal, 45);
    lv_obj_set_align(ui_MinCellVoltageVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MinCellVoltageVal, "1.8 V");
    lv_obj_set_style_text_color(ui_MinCellVoltageVal, lv_color_hex(0xD02424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MinCellVoltageVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MaxPackVoltageVal = lv_label_create(ui_BatteryInfoScreen);
    lv_obj_set_width(ui_MaxPackVoltageVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MaxPackVoltageVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MaxPackVoltageVal, -99);
    lv_obj_set_y(ui_MaxPackVoltageVal, 84);
    lv_obj_set_align(ui_MaxPackVoltageVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MaxPackVoltageVal, "26 V");
    lv_obj_set_style_text_color(ui_MaxPackVoltageVal, lv_color_hex(0xD02424), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MaxPackVoltageVal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryInfoHeader = lv_label_create(ui_BatteryInfoScreen);
    lv_obj_set_width(ui_BatteryInfoHeader, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryInfoHeader, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryInfoHeader, 1);
    lv_obj_set_y(ui_BatteryInfoHeader, -107);
    lv_obj_set_align(ui_BatteryInfoHeader, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatteryInfoHeader, "Battery Info");
    lv_obj_set_style_text_color(ui_BatteryInfoHeader, lv_color_hex(0xEEBA18), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BatteryInfoHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BatteryInfoHeader, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);


}
