// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: MBMS_Display

#include "ui.h"

void ui_PowerSelectionStatusScreen_screen_init(void)
{
    ui_PowerSelectionStatusScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PowerSelectionStatusScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MainPowerSwitchPanel = lv_obj_create(ui_PowerSelectionStatusScreen);
    lv_obj_set_width(ui_MainPowerSwitchPanel, 56);
    lv_obj_set_height(ui_MainPowerSwitchPanel, 38);
    lv_obj_set_x(ui_MainPowerSwitchPanel, 94);
    lv_obj_set_y(ui_MainPowerSwitchPanel, -66);
    lv_obj_set_align(ui_MainPowerSwitchPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MainPowerSwitchPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MainPowerSwitchVal = lv_label_create(ui_PowerSelectionStatusScreen);
    lv_obj_set_width(ui_MainPowerSwitchVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainPowerSwitchVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainPowerSwitchVal, 94);
    lv_obj_set_y(ui_MainPowerSwitchVal, -66);
    lv_obj_set_align(ui_MainPowerSwitchVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainPowerSwitchVal, "OFF");

    ui_MainPowerSwitchLabel = lv_label_create(ui_PowerSelectionStatusScreen);
    lv_obj_set_width(ui_MainPowerSwitchLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainPowerSwitchLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainPowerSwitchLabel, 86);
    lv_obj_set_y(ui_MainPowerSwitchLabel, -37);
    lv_obj_set_align(ui_MainPowerSwitchLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainPowerSwitchLabel, "Main Power Switch");

    ui_EN1Panel = lv_obj_create(ui_PowerSelectionStatusScreen);
    lv_obj_set_width(ui_EN1Panel, 56);
    lv_obj_set_height(ui_EN1Panel, 38);
    lv_obj_set_x(ui_EN1Panel, 94);
    lv_obj_set_y(ui_EN1Panel, 73);
    lv_obj_set_align(ui_EN1Panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_EN1Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EN1Val = lv_label_create(ui_PowerSelectionStatusScreen);
    lv_obj_set_width(ui_EN1Val, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EN1Val, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EN1Val, 94);
    lv_obj_set_y(ui_EN1Val, 74);
    lv_obj_set_align(ui_EN1Val, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EN1Val, "OFF");

    ui_EN1Label = lv_label_create(ui_PowerSelectionStatusScreen);
    lv_obj_set_width(ui_EN1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EN1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EN1Label, 95);
    lv_obj_set_y(ui_EN1Label, 105);
    lv_obj_set_align(ui_EN1Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EN1Label, "EN1");

    ui_ExternalShutdownCheck = lv_checkbox_create(ui_PowerSelectionStatusScreen);
    lv_checkbox_set_text(ui_ExternalShutdownCheck, "External Shutdown");
    lv_obj_set_width(ui_ExternalShutdownCheck, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ExternalShutdownCheck, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ExternalShutdownCheck, -69);
    lv_obj_set_y(ui_ExternalShutdownCheck, 29);
    lv_obj_set_align(ui_ExternalShutdownCheck, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_ExternalShutdownCheck, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_ExternalShutdownCheck, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_DCDCFaultCheck = lv_checkbox_create(ui_PowerSelectionStatusScreen);
    lv_checkbox_set_text(ui_DCDCFaultCheck, "DCDC Fault");
    lv_obj_set_width(ui_DCDCFaultCheck, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DCDCFaultCheck, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DCDCFaultCheck, -96);
    lv_obj_set_y(ui_DCDCFaultCheck, 56);
    lv_obj_set_align(ui_DCDCFaultCheck, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_DCDCFaultCheck, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_DCDCFaultCheck, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_DCDCOnCheck = lv_checkbox_create(ui_PowerSelectionStatusScreen);
    lv_checkbox_set_text(ui_DCDCOnCheck, "DCDC On");
    lv_obj_set_width(ui_DCDCOnCheck, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DCDCOnCheck, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DCDCOnCheck, -103);
    lv_obj_set_y(ui_DCDCOnCheck, -21);
    lv_obj_set_align(ui_DCDCOnCheck, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_DCDCOnCheck, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_DCDCOnCheck, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_ChargeFaultCheck = lv_checkbox_create(ui_PowerSelectionStatusScreen);
    lv_checkbox_set_text(ui_ChargeFaultCheck, "Charge Fault");
    lv_obj_set_width(ui_ChargeFaultCheck, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChargeFaultCheck, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChargeFaultCheck, -91);
    lv_obj_set_y(ui_ChargeFaultCheck, 82);
    lv_obj_set_align(ui_ChargeFaultCheck, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_ChargeFaultCheck, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_ChargeFaultCheck, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_ChargeOnCheck = lv_checkbox_create(ui_PowerSelectionStatusScreen);
    lv_checkbox_set_text(ui_ChargeOnCheck, "Charge On");
    lv_obj_set_width(ui_ChargeOnCheck, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChargeOnCheck, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChargeOnCheck, -99);
    lv_obj_set_y(ui_ChargeOnCheck, -46);
    lv_obj_set_align(ui_ChargeOnCheck, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_ChargeOnCheck, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_ChargeOnCheck, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_ThreeAmpOverCurrentCheck = lv_checkbox_create(ui_PowerSelectionStatusScreen);
    lv_checkbox_set_text(ui_ThreeAmpOverCurrentCheck, "3A Overcurrent");
    lv_obj_set_width(ui_ThreeAmpOverCurrentCheck, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThreeAmpOverCurrentCheck, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ThreeAmpOverCurrentCheck, -83);
    lv_obj_set_y(ui_ThreeAmpOverCurrentCheck, 107);
    lv_obj_set_align(ui_ThreeAmpOverCurrentCheck, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_ThreeAmpOverCurrentCheck, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_ThreeAmpOverCurrentCheck, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_KeyPanel = lv_obj_create(ui_PowerSelectionStatusScreen);
    lv_obj_set_width(ui_KeyPanel, 56);
    lv_obj_set_height(ui_KeyPanel, 38);
    lv_obj_set_x(ui_KeyPanel, 94);
    lv_obj_set_y(ui_KeyPanel, 5);
    lv_obj_set_align(ui_KeyPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_KeyPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_KeyLabel = lv_label_create(ui_PowerSelectionStatusScreen);
    lv_obj_set_width(ui_KeyLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KeyLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_KeyLabel, 95);
    lv_obj_set_y(ui_KeyLabel, 34);
    lv_obj_set_align(ui_KeyLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_KeyLabel, "Key");

    ui_KeyVal = lv_label_create(ui_PowerSelectionStatusScreen);
    lv_obj_set_width(ui_KeyVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_KeyVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_KeyVal, 94);
    lv_obj_set_y(ui_KeyVal, 6);
    lv_obj_set_align(ui_KeyVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_KeyVal, "OFF");

    ui_ChargeLVEnableCheck = lv_checkbox_create(ui_PowerSelectionStatusScreen);
    lv_checkbox_set_text(ui_ChargeLVEnableCheck, "Charge LV Enable");
    lv_obj_set_width(ui_ChargeLVEnableCheck, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChargeLVEnableCheck, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChargeLVEnableCheck, -75);
    lv_obj_set_y(ui_ChargeLVEnableCheck, -74);
    lv_obj_set_align(ui_ChargeLVEnableCheck, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_ChargeLVEnableCheck, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_ChargeLVEnableCheck, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_AuxBattDisableCheck = lv_checkbox_create(ui_PowerSelectionStatusScreen);
    lv_checkbox_set_text(ui_AuxBattDisableCheck, "AuxBattDisable");
    lv_obj_set_width(ui_AuxBattDisableCheck, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AuxBattDisableCheck, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AuxBattDisableCheck, -83);
    lv_obj_set_y(ui_AuxBattDisableCheck, 4);
    lv_obj_set_align(ui_AuxBattDisableCheck, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_AuxBattDisableCheck, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_AuxBattDisableCheck, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Label22 = lv_label_create(ui_PowerSelectionStatusScreen);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, 3);
    lv_obj_set_y(ui_Label22, -105);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "Power Selection Status");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0x9C18CD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);


}
